[libraries]
kotlinx-coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-immutableCollections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"

jda = "net.dv8tion:JDA:5.6.1"

junit-bom = "org.junit:junit-bom:5.13.1"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlinJvm = "org.jetbrains.kotlin.jvm:2.1.21"
shadow = "com.gradleup.shadow:9.0.0-beta16"
